In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/maharashtra-legislative-assembly-elections2019/Maharashtra Legislative Assembly Elemction Results 2019.csv


In [2]:
diabetes=pd.read_csv("https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv")
diabetes.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [3]:
"""
Define target(y) and features(x)
"""

y = diabetes['diabetes']
x = diabetes.drop(['diabetes'],axis=1)

In [4]:
"""
Train test split
"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=100)

In [5]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=500)

In [6]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=500)

In [7]:
model.fit_intercept

True

In [8]:
model.coef_

array([[ 1.03186872e-01,  3.85554833e-02, -1.12828523e-02,
         6.59810996e-04, -1.25282607e-03,  9.74622608e-02,
         1.16192580e+00,  2.33752775e-02]])

In [9]:
model.predict(x_test)

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [10]:
y=model.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
confusion_matrix(y_test,y)

array([[106,  21],
       [ 30,  35]])

In [12]:
accuracy_score(y_test,y)

0.734375

In [13]:
print(classification_report(y_test,y))

              precision    recall  f1-score   support

           0       0.78      0.83      0.81       127
           1       0.62      0.54      0.58        65

    accuracy                           0.73       192
   macro avg       0.70      0.69      0.69       192
weighted avg       0.73      0.73      0.73       192

